"""initial schema

Revision ID: e4dc77ad293a
Revises: 
Create Date: 2026-10-09 02:54:15.096707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e4dc77ad293a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmakers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('market_definitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('line_required', sa.Boolean(), nullable=False),
    sa.Column('selections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settlement', sa.Text(), nullable=False),
    sa.Column('required_data', sa.Text(), nullable=False),
    sa.Column('implementation_status', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_key', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_key')
    )
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('bookmaker_market_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bookmaker_id', sa.BigInteger(), nullable=False),
    sa.Column('market_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_market_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['market_definition_id'], ['market_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmaker_id', 'market_definition_id', 'provider_market_key', name='uq_bookmaker_market_map')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_id', name='uq_league_external')
    )
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_id', name='uq_team_external')
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_id', name='uq_player_external')
    )
    op.create_table('prediction_batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope_date', sa.Date(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('time_budget_seconds', sa.Integer(), nullable=False),
    sa.Column('source_data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running','succeeded','succeeded_with_warnings','failed','insufficient_data','no_qualifying_slips')", name='ck_batch_status'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_prediction_idempotency'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', name='uq_season_name')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('ht_home_goals', sa.Integer(), nullable=True),
    sa.Column('ht_away_goals', sa.Integer(), nullable=True),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','completed','postponed','cancelled','unknown')", name='ck_fixture_status'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_id', name='uq_fixture_external')
    )
    op.create_index('ix_fixtures_kickoff', 'fixtures', ['kickoff_at'], unique=False)
    op.create_table('slips',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('combined_odds', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('selection_count', sa.Integer(), nullable=False),
    sa.Column('joint_probability', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('joint_probability_method', sa.String(length=48), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('ev_status', sa.String(length=24), nullable=False),
    sa.Column('preparation_status', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_code', sa.String(length=64), nullable=True),
    sa.Column('booking_bookmaker', sa.String(length=64), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('joint_probability IS NULL OR (joint_probability >= 0 AND joint_probability <= 1)', name='ck_slip_joint_probability'),
    sa.ForeignKeyConstraint(['batch_id'], ['prediction_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_cards', sa.Integer(), nullable=True),
    sa.Column('away_cards', sa.Integer(), nullable=True),
    sa.Column('home_xg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('away_xg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmaker_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('market_key', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('decimal_odds', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mapping_status', sa.String(length=32), nullable=False),
    sa.Column('data_origin', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('decimal_odds > 1', name='ck_odds_gt_one'),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_fixture', 'odds_snapshots', ['fixture_id'], unique=False)
    op.create_table('player_match_statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_id', name='uq_player_fixture')
    )
    op.create_table('slip_evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slip_id', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('profit_units', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slip_id'], ['slips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('market_key', sa.String(length=64), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('probability', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('fair_odds', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('odds_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('data_quality', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('implementation_status', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='ck_prediction_probability'),
    sa.ForeignKeyConstraint(['batch_id'], ['prediction_batches.id'], ),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_batch', 'predictions', ['batch_id'], unique=False)
    op.create_table('slip_selections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slip_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('odds_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['slip_id'], ['slips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_id', 'position', name='uq_slip_position')
    )
    op.execute(
        """
        CREATE UNIQUE INDEX uq_odds_snapshot_identity
        ON odds_snapshots (
            fixture_id,
            bookmaker_id,
            market_key,
            selection,
            COALESCE(line, -9999),
            captured_at
        )
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_odds_snapshot_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'odds_snapshots are immutable';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER odds_snapshots_immutable
        BEFORE UPDATE OR DELETE ON odds_snapshots
        FOR EACH ROW EXECUTE FUNCTION prevent_odds_snapshot_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS odds_snapshots_immutable ON odds_snapshots")
    op.execute("DROP FUNCTION IF EXISTS prevent_odds_snapshot_mutation()")
    op.execute("DROP INDEX IF EXISTS uq_odds_snapshot_identity")
    op.drop_table('slip_selections')
    op.drop_index('ix_predictions_batch', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('slip_evaluations')
    op.drop_table('player_match_statistics')
    op.drop_index('ix_odds_fixture', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('match_statistics')
    op.drop_table('feature_snapshots')
    op.drop_table('slips')
    op.drop_index('ix_fixtures_kickoff', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('seasons')
    op.drop_table('prediction_batches')
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('ingestion_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('bookmaker_market_mappings')
    op.drop_table('providers')
    op.drop_table('model_versions')
    op.drop_table('market_definitions')
    op.drop_table('bookmakers')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
